# Generated by Django 5.1.1 on 2024-09-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riders", "0002_rider_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="busy",
            field=models.BooleanField(default=False),
        ),
    ]
