# Generated by Django 5.1.1 on 2024-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="riderearning",
            old_name="amount",
            new_name="amount_paid",
        ),
        migrations.AddField(
            model_name="riderearning",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="riderearning",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
