# Generated by Django 5.1.1 on 2024-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tenant",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("RIDER", "Rider"),
                    ("TENANT", "Tenant"),
                    ("ADMIN", "Admin"),
                    ("EMPLOYEE", "Employee"),
                ],
                max_length=255,
            ),
        ),
    ]
