# Generated by Django 5.1.1 on 2024-09-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("riders", "0003_rider_busy"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "delivery_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("In Transit", "In Transit"),
                            ("Complete", "Complete"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.order"
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="riders.rider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("In Transit", "In Transit"),
                            ("Complete", "Complete"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "next_status",
                    models.CharField(
                        choices=[
                            ("In Transit", "In Transit"),
                            ("Complete", "Complete"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliveries.delivery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
