# Generated by Django 5.1.1 on 2024-09-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0012_alter_client_client_uuid"),
        ("deliveries", "0004_alter_delivery_delivery_status_and_more"),
        ("riders", "0003_rider_busy"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("Single Order", "Single Order"),
                    ("Multiple Orders", "Multiple Orders"),
                ],
                default="Single Order",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Dispatched", "Dispatched"),
                            ("In Transit", "In Transit"),
                            ("Complete", "Complete"),
                            ("Pending Dispatch", "Pending Dispatch"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliveries.delivery",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.order"
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="riders.rider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
