# Generated by Django 5.1.1 on 2024-09-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0014_alter_client_client_uuid"),
        ("deliveries", "0005_delivery_delivery_type_deliveryorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.order",
            ),
        ),
    ]
