# Generated by Django 5.1.1 on 2024-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0007_deliveryorder_delivery_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryorder",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
