# Generated by Django 5.1.1 on 2024-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0008_deliveryorder_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
