# Generated by Django 5.1.1 on 2024-09-20 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0009_delivery_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryorder",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveryorders",
                to="deliveries.delivery",
            ),
        ),
    ]
