# Generated by Django 5.1.1 on 2024-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_location",
            field=models.JSONField(null=True),
        ),
    ]
