# Generated by Django 5.1.1 on 2024-09-13 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_alter_order_tenant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderstatusupdate",
            old_name="delivery",
            new_name="order",
        ),
    ]
