# Generated by Django 5.1.1 on 2024-09-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0008_alter_order_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
