# Generated by Django 5.1.1 on 2024-09-19 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_order_delivery_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_uuid",
            field=models.UUIDField(
                default=uuid.UUID("00998792-065c-4cfd-86ad-001b0ceeda4d")
            ),
        ),
    ]
