# Generated by Django 5.1.1 on 2024-09-19 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_client_client_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="additional_details",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_urgency",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_uuid",
            field=models.UUIDField(
                default=uuid.UUID("78af45e0-d97c-47bd-af2a-de9e96ba3d2f")
            ),
        ),
    ]
