# Generated by Django 5.1.1 on 2024-09-20 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0011_order_additional_details_order_delivery_urgency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_uuid",
            field=models.UUIDField(
                default=uuid.UUID("5a67ff0d-95b2-4a03-a655-610fe6eb492b")
            ),
        ),
    ]
