# Generated by Django 5.1.1 on 2024-09-20 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0014_alter_client_client_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_uuid",
            field=models.UUIDField(
                default=uuid.UUID("8feb8412-8ddb-4db4-a3e7-f48b19df325a")
            ),
        ),
    ]
