# Generated by Django 5.1.1 on 2024-09-20 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0017_alter_client_client_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_uuid",
            field=models.UUIDField(
                default=uuid.UUID("337bfef6-8632-4369-bff2-8fce2124c27e")
            ),
        ),
    ]
