# Generated by Django 5.1.1 on 2024-09-20 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0019_alter_client_client_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_uuid",
            field=models.UUIDField(
                default=uuid.UUID("2b8dedbb-fa97-4af3-a045-25345886bff4")
            ),
        ),
    ]
